### PR TITLE
New UI of login and Signup Page

### PR DESCRIPTION
**Pull request by Shashwat2412**

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
Please add the screenshots @Shashwat2412

**Comment by Shashwat2412** [comment]
Screenshot (3235)1
Screenshot (3236)2
Screenshot (3237)3
Screenshot (3238)4

**Comment by ShrutiMishra-2002** [comment]
@Shashwat2412 the work is not up to mark the items are not aligned in center , the heading is looking old school and the theme is not going with the website theme

**Comment by Shashwat2412** [comment]
Screenshot (3242)login
Screenshot (3243)signup

**Comment by ShrutiMishra-2002** [comment]
@Shashwat2412 this pr is already completed by other person !

**Pull request closed without merging**
