### PR TITLE
Added a Pre-loader to your website 

### PR DESCRIPTION
**Pull request by Rahulgarg01**
✔️Added a Pre-loader to your main website page. The link of preloader I have added is provided below....
  "https://i.pinimg.com/originals/e2/ce/da/e2ceda157f9fbf8f43ebd486692f575c.gif"
✔️If you wish to change it to any other preloader gif , you can do it simply by changing the url in loading section of style.css.
✔️It is visible for a short span of time but when your website will hold data It will be perfectly visible as website holding data takes some time to load.

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
@Rahulgarg01 added the screenshot how does it look on website

**Comment by Rahulgarg01** [comment]
It will run the emoji while loading the website

**Comment by Rahulgarg01** [comment]
Emoji will be running like:(small in size)👇👇

https://i.pinimg.com/originals/e2/ce/da/e2ceda157f9fbf8f43ebd486692f575c.gif

**Comment by ShrutiMishra-2002** [comment]
not working @Rahulgarg01 at all with website

**Pull request closed without merging**
