### PR TITLE
Fixed Header

### PR DESCRIPTION
**Pull request by ZaidKhan2002**
# After the change 

Screenshot 2022-10-10 at 3 23 39 PM

Screenshot 2022-10-10 at 3 23 56 PM

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
@ZaidKhan2002 please mention in detail about your changes

**Comment by ZaidKhan2002** [comment]
# Before The change
Screenshot 2022-10-10 at 10 24 20 PM
Screenshot 2022-10-10 at 10 24 34 PM

**Comment by ZaidKhan2002** [comment]
Added Fixed top and changed z-index.

**Comment by ZaidKhan2002** [comment]
Hey @ShrutiMishra-2002 whats up with this ?

**Comment by ZaidKhan2002** [comment]
Hey @ShrutiMishra-2002 is this valid or not or should I close it

**Comment by ZaidKhan2002** [comment]
I am closing this PR....

**Pull request closed without merging**
