### PR TITLE
Improve the UI design of room cards and home section

### PR DESCRIPTION
**Pull request by tahseenzahra**
This pr contains the improvement in the UI of 

- home section
- room text cards

### CODE REVIEW

**Comment by tahseenzahra** [comment]
before and after of home section:
- add blur effect with the text area to enhance the text

b3
a3

before and after of text card images
- image height is fixed

b1
a1

before and after of paragraph area of cards
- price field is made to appear side to side

b2
a2

**Comment by tahseenzahra** [comment]
Hey! @ShrutiMishra-2002 here are some changes I made to your repo to improve the UI.

**Comment by ShrutiMishra-2002** [comment]
@tahseenzahra all the changes are welcomed but please remove the blue effect !

**Comment by tahseenzahra** [comment]
> @tahseenzahra all the changes are welcomed but please remove the blur effect !

ok sure :slightly_smiling_face:

**Comment by tahseenzahra** [comment]
@ShrutiMishra-2002 changes are made

**Comment by tahseenzahra** [comment]
@ShrutiMishra-2002 can you please accept the pull request?

**Review by ShrutiMishra-2002 — APPROVED** [review]

**Pull request merged**
